"""Generate the FK validation fixture the C++ header claims exists.

WHY A FIXTURE AND NOT A LIVE CHECK
=================================
`fusion/include/otolith/leg_kin.hpp` asserted "validated against MuJoCo FK to
<2mm mean error (see test)". The test it pointed at did not do that: it asserted
`-0.35 < p.z() < -0.2` and a second one built a `Case` array and then discarded
it with `(void)cases`. The claim happened to be true -- 1.686 mm worst case --
but nothing checked it, so it was one edit away from being false.

C++ cannot load MuJoCo, so the truth has to come across as data. Same approach as
`fusion/src/gen_golden.cpp` for the Rust differential: generate once from the
authoritative implementation, check the generated file in, and have the C++ test
read it.

Both robots are covered, because the point of the seam is that the same filter
code serves a planar quadruped and a 6-DoF biped. Regenerate after any change to
`leg_kin.cpp` or `sim/otolith_sim/leg_model.py`:

    pixi run python mech/spec/build_fk_fixture.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import mujoco
import numpy as np

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "fusion" / "tests" / "fk_fixture.hpp"
N_POSES = 200

# scene, leg names, descriptor loader, root body, contact body per leg
ROBOTS = {
    "go2": (ROOT / "third_party/menagerie/unitree_go2/scene.xml",
            ("FL", "FR", "RL", "RR"), None, "base", "base"),
    "g1": (ROOT / ".work/g1scene/scene.xml",
           ("left", "right"), "load_g1", "pelvis", "{leg}_ankle_roll_link"),
    # Apollo needs no scene patch: its scene.xml already pairs the soles against
    # the floor. Its contact body is the FOOT, not an ankle link -- the last joint
    # in the chain is ankle_pd whose child is l_foot_link.
    "apollo": (ROOT / "third_party/menagerie/apptronik_apollo/scene.xml",
               ("left", "right"), "load_apollo", "base_link", "{side}_foot_link"),
    # OP3 needs the PATCHED scene for its named foot geoms, and the chain root is
    # `body_link` rather than a pelvis-named body.
    "op3": (ROOT / ".work/op3scene/scene.xml",
            ("left", "right"), "load_op3", "body_link", "{side}_ank_roll_link"),
}


def sample_poses(model, rng, n, band=0.6):
    """Random legal-ish qpos. `band` is the fallback width for unlimited joints.

    0.6 rad is narrow on purpose for Go2, where unlimited joints would otherwise let
    a free-swinging leg wander into poses that are valid but useless. OP3 has NO
    limits anywhere, so it passes the full pi instead -- there is no legal sub-range
    to respect, and the whole space is the honest thing to test.
    """
    q = np.zeros(model.nq)
    for j in range(1, model.njnt):
        if model.jnt_limited[j]:
            lo, hi = model.jnt_range[j]
            q[model.jnt_qposadr[j]] = rng.uniform(lo, hi)
        else:
            q[model.jnt_qposadr[j]] = rng.uniform(-band, band)
    return q


def main():
    sys.path.insert(0, str(ROOT / "sim"))
    from otolith_sim import leg_model as _lm
    from otolith_sim.leg_model import chain_fk, sole_world

    lines = [
        "// GENERATED by mech/spec/build_fk_fixture.py -- do not hand-edit.",
        "// Ground truth is MuJoCo's own FK, so this is an independent check on",
        "// fusion/src/leg_kin.cpp rather than a restatement of it.",
        "#pragma once",
        "#include <Eigen/Dense>",
        "",
        "namespace otolith {",
        "namespace fk_fixture {",
        "",
    ]

    for robot, (scene, legs, loader, root_body, contact_body) in ROBOTS.items():
        if not Path(scene).exists():
            raise SystemExit(f"{scene} missing -- build the scene first")
        model = mujoco.MjModel.from_xml_path(str(scene))
        d = mujoco.MjData(model)
        rng = np.random.default_rng(1234)

        # Legs whose geometry is a point we can name: for Go2 that is the named
        # foot geom; for G1 the mean of the foot's contact spheres, which is what
        # the sole point is defined to be.
        if robot == "go2":
            geom = [model.geom(n).id for n in legs]
            cbody = [model.body(contact_body).id] * len(legs)
        else:
            lm = getattr(_lm, loader)(model)
            geom = [[model.geom(n).id for n in lm.contact_geoms[leg]] for leg in legs]
            cbody = [model.body(contact_body.format(
                leg=leg, side="l" if leg == "left" else "r")).id for leg in legs]

        qs, refs = [], []
        base = model.body(root_body).id
        for _ in range(N_POSES):
            q = sample_poses(model, rng, N_POSES, band=np.pi if robot == "op3" else 0.6)
            d.qpos[:] = q
            mujoco.mj_forward(model, d)
            Rb = d.xmat[base].reshape(3, 3)
            for li, leg in enumerate(legs):
                if robot == "go2":
                    ang = [float(d.qpos[model.jnt_qposadr[model.joint(f"{leg}_{j}_joint").id]])
                           for j in ("hip", "thigh", "calf")]
                    world = d.geom_xpos[geom[li]].copy()
                else:
                    ang = list(_lm.chain_angles(model, d, lm.chain(leg)))
                    # Reference the SOLE POINT through MuJoCo's own foot-body
                    # transform, not the mean of the contact geom centres: Apollo's
                    # sole is the box's bottom face, 9 mm below its centre, and
                    # averaging centres would silently test the wrong point.
                    off = lm.sole[leg]
                    R = d.xmat[cbody[li]].reshape(3, 3)
                    world = d.xpos[cbody[li]] + R @ off
                qs.append(ang)
                refs.append(Rb.T @ (world - d.xpos[base]))

        lines.append(f"// {robot}: {len(qs)} (leg-pose) samples")
        lines.append(f"inline constexpr int k{robot.capitalize()}Samples = {len(qs)};")
        lines.append(f"inline constexpr int k{robot.capitalize()}Dof = {len(qs[0])};")
        lines.append(f"inline const double k{robot.capitalize()}Q[{len(qs)}][{len(qs[0])}] = {{")
        for a in qs:
            lines.append("    {" + ", ".join(f"{v:+.12g}" for v in a) + "},")
        lines.append("};")
        lines.append(f"inline const double k{robot.capitalize()}Ref[{len(qs)}][3] = {{")
        for r in refs:
            lines.append("    {" + ", ".join(f"{v:+.12g}" for v in r) + "},")
        lines.append("};")
        lines.append("")

    lines.append("} // namespace fk_fixture")
    lines.append("} // namespace otolith")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({' + '.join(ROBOTS)} FK truth from MuJoCo)")


if __name__ == "__main__":
    main()